### ISSUE TITLE
Dask related issue

### ISSUE THREAD

**Issue by stoormgeo** [geodesymiami/MiNoPy#51]
Hi,
From last update i have this issue with Dask:
Can it be temporarily disabled? Setting in mintpy.compute.cluster is not working for me.
Thx

`------- start parallel processing using Dask -------
Traceback (most recent call last):
  File "/insar/MiNoPy/minopy/phase_to_range.py", line 372, in <module>
    main()
  File "/insar/MiNoPy/minopy/phase_to_range.py", line 296, in main
    cluster_obj = cluster.DaskCluster('local', inps.num_worker)
  File "/insar/MintPy/mintpy/objects/cluster.py", line 160, in __init__
    self.num_worker = self.format_num_worker(self.cluster_type, self.num_worker)
  File "/insar/MintPy/mintpy/objects/cluster.py", line 380, in format_num_worker
    elif num_worker.endswith('%'):
AttributeError: 'int' object has no attribute 'endswith'`

**Comment by mirzaees** [comment]
Hi @stoormgeo 
I just committed an update and there is a fix for this problem
for phase_to_range step, if you don't want to use parallel processors, please set the number of workers to 1 in minopyApp.cfg

**Comment by stoormgeo** [comment]
@mirzaees 
Thx for fix!

> Hi @stoormgeo I just committed an update and there is a fix for this problem for phase_to_range step, if you don't want to use parallel processors, please set the number of workers to 1 in minopyApp.cfg
