### ISSUE TITLE
Load_slc_Geometry missing STARTING_RANGE key value - ISCE Stripmap 

### ISSUE THREAD

**Issue by jsb613** [geodesymiami/MiNoPy#62]
Hi, 

I'm encountering an issue at the load_slc_geometry step when ingesting TSX data prepared with ISCE stripmapStack. The issue emerges when creating the geometryRadar.h5 file. range_distance in mintpy/utils/utils0.py is running into a missing key error.

I'm wondering if I am perhaps not providing the correct values in my template (see below) or if there is some code I need to modify for ISCE stripmap. 

Any insights would be appreciated, thanks. Furthermore, everywhere there was a isceobj import I had to precede it with an import isce. 

Error from console:

minopyApp.py minopy_template_ascd.cfg --dostep load_slc_geometry --dir ./minopy2

create HDF5 file /home/user/processing_dir/cluster/minopy2/inputs/geometryRadar.h5 with a mode
create dataset /height             of <class 'numpy.float32'>   in size of (2580, 3568) with compression = lzf
create dataset /latitude           of <class 'numpy.float32'>   in size of (2580, 3568) with compression = lzf
create dataset /longitude          of <class 'numpy.float32'>   in size of (2580, 3568) with compression = lzf
create dataset /incidenceAngle     of <class 'numpy.float32'>   in size of (2580, 3568) with compression = lzf
create dataset /azimuthAngle       of <class 'numpy.float32'>   in size of (2580, 3568) with compression = lzf
create dataset /shadowMask         of <class 'numpy.bool_'>     in size of (2580, 3568) with compression = lzf
prepare slantRangeDistance ...
Traceback (most recent call last):
  File "/home/user/software/MiNoPy/minopy/load_slc_geometry.py", line 247, in <module>
    main()
  File "/home/user/software/MiNoPy/minopy/load_slc_geometry.py", line 101, in main
    geomRadarObj.write2hdf5(outputFile=inps.out_file[1],
  File "/home/user/software/MiNoPy/minopy/objects/geometryStack.py", line 223, in write2hdf5
    data = self.get_slant_range_distance(box=box)
  File "/home/user/software/MintPy/mintpy/objects/stackDict.py", line 416, in get_slant_range_distance
    data = ut.range_distance(self.extraMetadata,
  File "/home/user/software/MintPy/mintpy/utils/utils0.py", line 52, in range_distance
    range_n, dR = float(atr['STARTING_RANGE']), float(atr['RANGE_PIXEL_SIZE'])
KeyError: 'STARTING_RANGE'

Custom template file used:

minopy.multiprocessing.numProcessor              = 2
minopy.load.processor      = isce
minopy.load.updateMode     = auto
minopy.load.compression    = auto
minopy.load.autoPath       = auto

minopy.load.slcFile        = /home/user/processing_dir/cluster/merged/SLC/**/**.slc

Metadata file set to reference file the stack (ISCE)
minopy.load.metaFile       = /home/user/processing_dir/cluster/merged/SLC/20210506/referenceShelve/data.dat
minopy.load.baselineDir    = /home/user/processing_dir/cluster/baselines
minopy.load.demFile          = /home/user/processing_dir/cluster/merged/geom_reference/hgt.rdr
minopy.load.lookupYFile      = /home/user/processing_dir/cluster/merged/geom_reference/lat.rdr
minopy.load.lookupXFile      = /home/user/processing_dir/cluster/merged/geom_reference/lon.rdr
minopy.load.incAngleFile     = /home/user/processing_dir/cluster/merged/geom_reference/los.rdr
minopy.load.azAngleFile      = /home/user/processing_dir/cluster/merged/geom_reference/los.rdr
minopy.load.shadowMaskFile   = /home/user/processing_dir/cluster/merged/geom_reference/shadowMask.rdr
minopy.load.waterMaskFile    = None
minopy.load.unwFile        = /home/user/processing_dir/cluster/minopy2/inverted/interferograms_sequential/**/**fine**.unw
minopy.load.corFile        = /home/user/processing_dir/cluster/minopy2/inverted/interferograms_sequential/**/**fine**.cor
minopy.load.connCompFile   = /home/user/processing_dir/cluster/minopy2/inverted/interferograms_sequential/**/**.unw.conncomp
minopy.inversion.patchSize                = 200
minopy.interferograms.numSequential      = 10

mintpy.compute.cluster     = local
mintpy.compute.numWorker   = 8
mintpy.reference.lalo     =  auto
mintpy.unwrapError.method          = auto
mintpy.troposphericDelay.method = pyaps
mintpy.reference.date = no

**Comment by mirzaees** [comment]
Hi @jsb613 
I think I have seen this error before, it is probably related to the isce metadata. I remember ISCE did not create one of the products for reference image (probably .xml). please use ls to compare all products in `/home/user/processing_dir/cluster/merged/SLC/20210506/referenceShelve` and in one of the other SLCs referenceShelve directories. if the `20210506` is missing something, then use another image referenceShelve directory for setting to `minopy.load.metaFile`. They are all similar.

Regarding isceobj import, thank you for mentioning that. I have added the following to my PYTHONPATH, and installed ISCE via conda. Please try adding this to your PYTHONPATH and let me know if it solves the problem for you

`export PYTHONPATH=${PYTHONPATH}:${ISCE_HOME}:${ISCE_HOME}/components`

**Comment by jsb613** [comment]
Hey @mirzaees 

The isceobj issue was resolved with modifying PYTHONPATH. Thanks. 

The geometryRadar.h5 was not solved by simply changing minopy.load.metaFile to an SLC that was not the reference. However, there was an XML file missing in comparison to other SLCs. 

I debugged and found the following. 

1. Metadata is properly being extracted from the rsc files. 

2. geometryRadar.h5 was never properly created since the required metadata was missing for range_distance() in utils0.py.

3. To ensure the required metadata was passed, in read_inps_dict2geometry_dict_object (load_slc_geometry.py) a modification was made to line 234 where extraMetadata=slcRadarMetadata was set to extraMetadata=None 

As a result, when the constructor is called for GeometryDict (geometryStack.py) it will read metadata from the first geometry file (hgt.rdr) and find ['STARTING_RANGE', 'RANGE_PIXEL_SIZE']. 

I’m not sure what effect this will have elsewhere or with other sensors, but it appears to have properly created the geometryRadar.h5 file with its metadata.

**Comment by mirzaees** [comment]
@jsb613 Thank you for confirming

The .rsc files were created last time without proper metadata and the code does not overwrite them
Did you delete them before running again? maybe doing so, would solve the problem

If all the geometry files are read properly with your modification, there should not be future issues, however it has to be tested
